[package]
name = "troposphere"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
troposphere-lib = { path = "../../lib/troposphere-lib" }

serde = { version = "^1", features = ["derive"] }


# meta
tracing.workspace = true
thiserror.workspace = true

# chat
ed25519-dalek = { workspace = true, features = ["alloc", "pkcs8", "serde"] }
# uuid.workspace = true
rand.workspace = true
# dashmap.workspace = true

# captp
# syrup.workspace = true
## async
futures.workspace = true
parking_lot.workspace = true

manganis = { git = "https://github.com/DioxusLabs/collect-assets" }

pulldown-cmark = "^0.10"

dashmap.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
clap = { version = "^4.5", features = ["derive", "env"] }
lazy_static = "^1"
figment = { version = "^0.10", features = ["toml", "env"] }
directories = "^5"
toml = { version = "^0.8", features = ["display"] }

tracing-subscriber = { version = "^0.3", features = [
  "time",
  "env-filter",
  "parking_lot",
  "local-time",
  "json",
] }
time = { version = "^0.3", features = ["formatting", "local-offset", "macros"] }

dioxus = { git = "https://github.com/DioxusLabs/dioxus", features = [
  "desktop",
] }
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus", features = [
  "devtools",
  "transparent",
  "tokio",
] }
wry = { version = "^0.37", features = [
  "tracing",
  "transparent",
  "linux-body",
  "fullscreen",
] }

rexa = { workspace = true, features = [] }
rexa-netlayers = { workspace = true, features = ["datastream-tcp"] }

tokio = { workspace = true, features = [
  "rt-multi-thread",
  "net",
  "signal",
  "parking_lot",
  "tracing",
] }

mdns-sd = { version = "^0.10" }
gethostname = "^0.4"
# for encoding verifying keys in mdns properties
base64 = "^0.22"

# HACK :: https://github.com/kotauskas/interprocess/issues/32
interprocess = { version = "^1", features = ["tokio_support"] }

[target.'cfg(target_family = "unix")'.dependencies]
pnet = { version = "^0.34" }

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = { version = "^0.2", features = ["js"] }

dioxus = { git = "https://github.com/DioxusLabs/dioxus", features = ["web"] }
dioxus-web = { git = "https://github.com/DioxusLabs/dioxus", features = [] }

rexa = { workspace = true, features = [] }
rexa-netlayers = { workspace = true, features = ["datastream"] }
tokio = { workspace = true, features = ["rt"] }

figment = { version = "^0.10", features = [] }

wasm-bindgen = { version = "^0.2" }
web-sys = { version = "^0.3", features = [
  "Window",
  "Navigator",
  "StorageManager",
] }
gloo-storage = { version = "^0.3" }

[features]
default = []

[lints]
workspace = true
